const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const machine=$('#machine'),statusEl=$('#status'),creditEl=$('#credit'),logEl=$('#eventLog'),bet=$('#bet'),start=$('#start'),stops=$$('.stop'),flowers=$$('.flower');
const state={version:'0.4.0',credit:50,bet:false,phase:'idle',stopIndex:0,scene:null,lamp:false,locks:[false,false,false],audio:null,master:null,fps:0,fx:{stopBursts:0,bonusBursts:0,cameraImpulses:0,poolSize:24,blendMode:'ADD',glassSweep:true,spinFrames:0,spinTravel:0,visualTravel:0,reelModel:'RAF_CONTINUOUS_PHASER_OBJECTS',reelDirection:'TOP_TO_BOTTOM',motionProfile:'ACCEL_CRUISE_BRAKE_SETTLE'}};
function log(a,b=''){const t=new Date().toTimeString().slice(0,8);logEl.textContent=(logEl.textContent+`${t}  ${a}${b?'  '+b:''}\n`).split('\n').slice(-34).join('\n');}
function phase(p,label){state.phase=p;machine.dataset.phase=p;if(label)statusEl.textContent=label;log('PHASE',p)}
async function unlock(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!state.audio){state.audio=new AC();state.master=state.audio.createGain();state.master.gain.value=.12;state.master.connect(state.audio.destination)}if(state.audio.state==='suspended')await state.audio.resume()}
function tone(f,d=.05,v=.18,type='triangle'){if(!state.audio||state.audio.state!=='running')return;const o=state.audio.createOscillator(),g=state.audio.createGain(),n=state.audio.currentTime;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,n);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(state.master);o.start();o.stop(n+d+.02)}
const SYMBOLS=[{k:'seven',t:'7',c:'#c8202d',sub:'YUYU'},{k:'cherry',t:'●',c:'#d82435',sub:'CHERRY'},{k:'bell',t:'◆',c:'#e1a91d',sub:'BELL'},{k:'replay',t:'↻',c:'#2877c7',sub:'REPLAY'},{k:'bar',t:'BAR',c:'#262229',sub:'YUYU'},{k:'leaf',t:'✦',c:'#2f9b61',sub:'LEAF'},{k:'seven',t:'7',c:'#c8202d',sub:'YUYU'},{k:'bell',t:'◆',c:'#e1a91d',sub:'BELL'},{k:'cherry',t:'●',c:'#d82435',sub:'CHERRY'},{k:'replay',t:'↻',c:'#2877c7',sub:'REPLAY'},{k:'bar',t:'BAR',c:'#262229',sub:'YUYU'},{k:'leaf',t:'✦',c:'#2f9b61',sub:'LEAF'}];
const SPACING=36,LOOP=252,mod=(n,m)=>((n%m)+m)%m;
// Motion constants are tuning hypotheses, not measured real-machine specifications.
const MOTION={launchSpeed:84,accel:2900,cruise:[520,538,556],brakeDecel:2550,brakeMs:[122,134,146],settleSpeed:270};
class YuyuScene extends Phaser.Scene{
 constructor(){super('yuyu');this.reels=[];this.fxPool=[];this.fxCursor=0;this.rafId=0;this.lastRaf=0}
 create(){state.scene=this;this.cameras.main.setBackgroundColor('#161314');this.add.rectangle(171,88,342,176,0xeee8dc);this.add.rectangle(171,88,336,170,0xffffff,.12).setStrokeStyle(3,0x171316,.9).setDepth(31);for(let i=0;i<3;i++)this.makeReel(i);[52,88,124].forEach(y=>this.add.rectangle(171,y,330,1,0x4d4042,.16).setDepth(20));[114,227].forEach(x=>this.add.rectangle(x,88,2,166,0x1b1718,.45).setDepth(21));this.add.rectangle(171,88,330,164,0xffffff,0).setStrokeStyle(1,0xf6ead5,.65).setDepth(32);this.buildOptics();this.buildFxPool();this.startReelLoop();log('PHASER_FX','READY');log('REEL_DRIVER','RAF_ATTACHED');log('REEL_DIRECTION','TOP_TO_BOTTOM');log('MOTION_PROFILE','ACCEL_CRUISE_BRAKE_SETTLE');log('SCENE','READY')}
 buildOptics(){this.glassGlow=this.add.rectangle(171,88,42,154,0xffffff,.055).setAngle(-12).setDepth(34).setBlendMode(Phaser.BlendModes.ADD);this.glassGlow.x=-30;this.tweens.add({targets:this.glassGlow,x:372,duration:3600,repeat:-1,repeatDelay:1500});this.edgeL=this.add.rectangle(14,88,18,162,0xffdbe9,.035).setDepth(33).setBlendMode(Phaser.BlendModes.ADD);this.edgeR=this.add.rectangle(328,88,18,162,0xffdbe9,.035).setDepth(33).setBlendMode(Phaser.BlendModes.ADD)}
 buildFxPool(){for(let i=0;i<state.fx.poolSize;i++){const p=this.add.circle(-30,-30,2+(i%3),0xff77c6,0).setDepth(50).setBlendMode(Phaser.BlendModes.ADD);this.fxPool.push(p)}}
 makeReel(i){const x=58+i*113,r={index:i,x,offset:i*72,travel:i*72,symbolShift:i*2,speed:0,targetSpeed:MOTION.cruise[i],spinning:false,locked:false,braking:false,stage:'idle',brakeDeadline:0,settleTarget:null,probeIndex:0,cells:[]};this.add.rectangle(x,88,102,166,0xf7f0e2).setStrokeStyle(1,0x9d9181).setDepth(1);this.add.rectangle(x-44,88,10,162,0x000000,.08).setDepth(8);this.add.rectangle(x+44,88,10,162,0x000000,.08).setDepth(8);this.add.rectangle(x,88,16,160,0xffffff,.035).setDepth(8).setBlendMode(Phaser.BlendModes.ADD);for(let j=0;j<7;j++){const plate=this.add.rectangle(x,0,91,34,0xfffcf2).setStrokeStyle(1,0xd5c8b5).setDepth(4);const label=this.add.text(x,0,'',{fontFamily:'Arial Black,system-ui,sans-serif',fontStyle:'900',fontSize:'24px',color:'#222'}).setOrigin(.5,.57).setDepth(6);const sub=this.add.text(x,0,'',{fontFamily:'system-ui,sans-serif',fontStyle:'800',fontSize:'5px',color:'#555',letterSpacing:1}).setOrigin(.5).setDepth(7);r.cells.push({plate,label,sub,j})}this.reels.push(r);this.paint(r)}
 paint(r){const travel=Number.isFinite(r.travel)?r.travel:0,turns=Math.floor(travel/LOOP);r.cells.forEach((c,k)=>{const local=mod(k*SPACING+travel+LOOP/2,LOOP)-LOOP/2,y=88+local,s=SYMBOLS[mod(k-turns*7+r.symbolShift,SYMBOLS.length)];c.plate.y=y;c.label.y=y-2;c.sub.y=y+11;c.label.setText(s.t).setColor(s.c);c.sub.setText(s.sub).setColor(s.k==='bar'?'#7b6b51':s.c);const visible=y>=19&&y<=157,edge=Math.min(1,Math.max(.38,1-Math.abs(y-88)/118));c.plate.setVisible(visible).setAlpha((r.spinning?.92:1)*edge);c.label.setVisible(visible).setAlpha((r.spinning?.9:1)*edge);c.sub.setVisible(visible).setAlpha((r.spinning?.88:1)*edge)})}
 startReelLoop(){if(this.rafId)return;const tick=(now)=>{const delta=this.lastRaf?Math.min(Math.max(now-this.lastRaf,4),50):16.666;this.lastRaf=now;this.reelFrame(delta,now);this.rafId=requestAnimationFrame(tick)};this.rafId=requestAnimationFrame(tick)}
 reelFrame(delta,now){const dt=delta/1000;let moving=0;this.reels.forEach((r,i)=>{if(!r.spinning)return;if(r.stage==='accelerating'){r.speed=Math.min(r.targetSpeed,r.speed+MOTION.accel*dt);if(r.speed>=r.targetSpeed){r.stage='cruise';log('REEL_SPEED',`CRUISE_R${i+1}:${Math.round(r.speed)}`)}}else if(r.stage==='braking'){r.speed=Math.max(MOTION.settleSpeed,r.speed-MOTION.brakeDecel*dt);if(now>=r.brakeDeadline)this.beginSettle(i)}if(r.stage==='settling'){const remain=r.settleTarget-r.travel;if(remain<=.001){this.lock(i);return}const d=Math.min(remain,MOTION.settleSpeed*dt);r.travel+=d;r.offset=mod(r.travel,432);state.fx.spinTravel+=d;state.fx.visualTravel+=d;moving++;this.paint(r);if(r.settleTarget-r.travel<=.001)this.lock(i);return}const d=r.speed*dt;r.travel+=d;r.offset=mod(r.travel,432);state.fx.spinTravel+=d;state.fx.visualTravel+=d;moving++;this.paint(r)});if(moving){state.fx.spinFrames++;if(state.fx.spinFrames===2)log('REEL_ROTATION','VISIBLE_ACTIVE')}const fps=1000/delta;state.fps=state.fps?state.fps*.9+fps*.1:fps;$('#fps').textContent=`${Math.round(state.fps)} FPS`}
 begin(){this.reels.forEach((r,i)=>{r.spinning=true;r.braking=false;r.locked=false;r.stage='accelerating';r.targetSpeed=MOTION.cruise[i];r.speed=MOTION.launchSpeed;r.brakeDeadline=0;r.settleTarget=null;this.paint(r);r.probeIndex=r.cells.reduce((best,c,idx)=>Math.abs(c.label.y-86)<Math.abs(r.cells[best].label.y-86)?idx:best,0)});state.locks=[false,false,false];state.fx.spinFrames=0;state.fx.spinTravel=0;state.fx.visualTravel=0;try{this.tweens.add({targets:[this.edgeL,this.edgeR],alpha:.075,duration:140,yoyo:true})}catch(e){log('FX_ERROR',`BEGIN:${String(e?.message||e)}`)}log('REEL','SPIN');log('REEL_MODEL','RAF_CONTINUOUS_PHASER_OBJECTS');log('REEL_DIRECTION','TOP_TO_BOTTOM');log('REEL_SPEED',`LAUNCH:${MOTION.launchSpeed}`)}
 requestStop(i){const r=this.reels[i];if(!r.spinning||r.braking||r.stage==='settling')return;r.braking=true;r.stage='braking';r.brakeDeadline=performance.now()+MOTION.brakeMs[i];log('REEL_BRAKE',`R${i+1}:${Math.round(r.speed)}`)}
 beginSettle(i){const r=this.reels[i];if(!r.spinning||r.stage==='settling')return;r.stage='settling';r.braking=false;r.speed=MOTION.settleSpeed;r.settleTarget=Math.ceil(r.travel/SPACING)*SPACING;if(r.settleTarget-r.travel<2)r.settleTarget+=SPACING;log('REEL_SETTLE',`R${i+1}->${Math.round(r.settleTarget)}`)}
 stopFx(i){const x=this.reels[i].x;state.fx.stopBursts++;try{state.fx.cameraImpulses++;this.cameras.main.shake(55,.0018);for(let n=0;n<6;n++){const p=this.fxPool[this.fxCursor++%this.fxPool.length],a=(Math.PI*2*n/6)+(i*.35);p.setPosition(x,88).setAlpha(.42).setScale(.7);this.tweens.add({targets:p,x:x+Math.cos(a)*(18+n*2),y:88+Math.sin(a)*(18+n*2),alpha:0,scale:1.5,duration:170+n*12})}const ring=this.add.circle(x,88,13,0xffffff,0).setStrokeStyle(2,0xff8dcc,.55).setDepth(49).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:ring,scale:2.8,alpha:0,duration:190,onComplete:()=>ring.destroy()})}catch(e){log('PHASER_FX_ERROR',String(e?.message||e))}log('PHASER_FX',`STOP_BURST_R${i+1}`)}
 lock(i){const r=this.reels[i];if(r.locked)return;r.spinning=false;r.braking=false;r.speed=0;r.stage='locked';r.travel=r.settleTarget??Math.round(r.travel/SPACING)*SPACING;r.offset=mod(r.travel,432);r.locked=true;this.paint(r);state.locks[i]=true;log('REEL_ALIGN',`R${i+1}`);log('LOCK',String(i+1));tone(155+i*18,.035,.16,'sine');this.stopFx(i)}
 bonusFx(){state.fx.bonusBursts++;try{state.fx.cameraImpulses++;this.cameras.main.shake(90,.0024);this.tweens.add({targets:[this.edgeL,this.edgeR],alpha:.16,duration:110,yoyo:true,repeat:1});for(let n=0;n<18;n++){const p=this.fxPool[this.fxCursor++%this.fxPool.length],x=25+(n%9)*36,y=48+(n%3)*38;p.setPosition(x,y).setAlpha(.55).setScale(.8);this.tweens.add({targets:p,y:y-18-(n%4)*5,alpha:0,scale:1.8,duration:260+(n%5)*40,delay:(n%6)*18})}}catch(e){log('PHASER_FX_ERROR',String(e?.message||e))}log('PHASER_FX','BONUS_BURST')}
}
new Phaser.Game({type:Phaser.WEBGL,width:342,height:176,parent:'game',transparent:false,scene:YuyuScene,render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
bet.addEventListener('click',async()=>{await unlock();if(state.phase!=='idle')return;state.bet=true;state.credit--;creditEl.textContent=`CREDIT ${state.credit}`;start.disabled=false;tone(760,.045,.16);phase('bet','STARTできます');log('BET','1')});
start.addEventListener('click',async()=>{await unlock();if(!state.bet||!state.scene)return;state.stopIndex=0;start.disabled=true;stops.forEach(b=>b.disabled=false);state.scene.begin();tone(105,.11,.12,'sawtooth');phase('spin','REELS SPINNING');log('GAME_EVENT','LEVER_ON')});
stops.forEach((b,i)=>b.addEventListener('click',async()=>{await unlock();if(i!==state.stopIndex||state.phase!=='spin')return;b.disabled=true;state.scene.requestStop(i);tone(235+i*22,.045,.18);state.stopIndex++;log('GAME_EVENT',`STOP_${i+1}`);if(state.stopIndex===3){stops.forEach(x=>x.disabled=true);const wait=()=>{if(!state.locks.every(Boolean)){setTimeout(wait,20);return}phase('judge','……');setTimeout(()=>{state.lamp=true;flowers.forEach(f=>f.classList.add('on'));state.scene.bonusFx();phase('bonus','BONUS');tone(523,.18,.17);setTimeout(()=>tone(659,.22,.14),70);log('YUYU','FLOWER_LAMP_ON');log('GAME_EVENT','BONUS_ENTER')},360)};wait()}}));
window.__YUYU_STATE__=()=>({version:state.version,phase:state.phase,credit:state.credit,lamp:state.lamp,locks:[...state.locks],audio:{hasContext:!!state.audio,contextState:state.audio?.state||'none'},phaser:{version:Phaser.VERSION,renderer:state.scene?.game?.renderer?.type??null,...state.fx},motion:{...MOTION},reels:state.scene?.reels.map((r,i)=>({index:i+1,offset:r.offset,travel:r.travel,speed:r.speed,targetSpeed:r.targetSpeed,stage:r.stage,latticeError:r.locked?Math.abs(r.travel-Math.round(r.travel/36)*36):null,locked:r.locked,braking:r.braking,spinning:r.spinning,sampleY:r.cells?.[0]?.label?.y??null,probeIndex:r.probeIndex,probeY:r.cells?.[r.probeIndex]?.label?.y??null}))||[]});
window.__YUYU_RESET__=()=>{state.bet=false;state.stopIndex=0;state.lamp=false;flowers.forEach(f=>f.classList.remove('on'));stops.forEach(x=>x.disabled=true);start.disabled=true;phase('idle','BETしてください')};
log('PATCH','REEL_MOTION_PROFILE_V0_4_0');