const { test, expect } = require('@playwright/test');
const fs=require('fs'),path=require('path');const evidenceDir=path.join(__dirname,'evidence-yuyu');const targetPath='/research/yuyu_normal_type_lab/index.html?v=060';
async function shot(page,name){await page.screenshot({path:path.join(evidenceDir,`${name}.png`),fullPage:true});}
async function waitLog(page,text){await expect.poll(async()=>page.locator('#eventLog').textContent(),{timeout:9000}).toContain(text);}
async function state(page){return page.evaluate(()=>window.__YUYU_STATE__?.()||null);}
test('YUYU v0.6.0 Phaser cabinet compositor + preserved reel core + full 1G iPhone playtest',async({page})=>{
 fs.mkdirSync(evidenceDir,{recursive:true});const base=process.env.PLAYTEST_BASE_URL||'http://127.0.0.1:4173';const url=new URL(targetPath,base).toString();const consoleMessages=[],pageErrors=[];
 page.on('console',m=>consoleMessages.push(`[${m.type()}] ${m.text()}`));page.on('pageerror',e=>pageErrors.push(String(e)));
 await page.goto(url,{waitUntil:'networkidle'});await expect(page.locator('#machine')).toBeVisible();await expect(page.locator('header small')).toContainText('YUYU v0.6.0');
 await waitLog(page,'PATCH  SYMBOL_PROPORTION_V0_5_2');await waitLog(page,'PATCH  CABINET_PHYSICAL_V0_5_3');await waitLog(page,'PATCH  PHASER_CABINET_COMPOSITOR_V0_6_0');await waitLog(page,'CABINET_STAGE  PHASER_COMPOSITOR_READY');
 await page.waitForTimeout(450);let s=await state(page);
 expect(s.version).toBe('0.6.0');expect(s.phaser.renderer).toBe(2);expect(String(s.phaser.version)).toContain('4.2.1');expect(s.phaser.reelDirection).toBe('TOP_TO_BOTTOM');expect(s.phaser.motionProfile).toBe('ACCEL_CRUISE_BRAKE_SETTLE');expect(s.phaser.depthMode).toBe('PERMANENT_2_5D_REEL_STACK');expect(s.phaser.symbolSurface).toBe('PRINT_GRADE_SVG_MESH2D');expect(s.phaser.symbolSpacing).toBe('36_PITCH_30_FACE_6_GAP');expect(s.phaser.symbolProportion).toBe('WIDE_69_44X30_KEEP_6_GAP');expect(s.phaser.cabinetRenderer).toBe('PHASER_2_5D_COMPOSITOR_V060');expect(s.phaser.cabinetStageGame).toBe(true);
 expect(s.reference.reference).toBe('HANAHANA_CLASS_NORMAL_TYPE');expect(s.symbolPrint.errors).toEqual([]);expect(s.symbolSpacing.errors).toEqual([]);expect(s.symbolProportion.errors).toEqual([]);expect(s.cabinetPhysical.errors).toEqual([]);
 expect(s.symbolSpacing.reelPitchPx).toBe(36);expect(s.symbolSpacing.visibleSymbolHeightPx).toBe(30);expect(s.symbolSpacing.nominalGapPx).toBe(6);expect(s.symbolProportion.visibleSymbolWidthPx).toBe(69.44);
 expect(s.cabinetStage.enabled).toBe(true);expect(s.cabinetStage.separatePhaserStage).toBe(true);expect(s.cabinetStage.gameRenderer).toBe(2);expect(s.cabinetStage.meshRails).toBe(2);expect(s.cabinetStage.orderedIndices).toBe(true);expect(s.cabinetStage.materialPlanes).toBeGreaterThanOrEqual(12);expect(s.cabinetStage.lampOptics).toBe(8);expect(s.cabinetStage.controlRings).toBe(8);expect(s.cabinetStage.movingGlass).toBe(false);expect(s.cabinetStage.reelGeometryChanged).toBe(false);expect(s.cabinetStage.symbolGeometryChanged).toBe(false);expect(s.cabinetStage.errors).toEqual([]);
 await expect(page.locator('html')).toHaveAttribute('data-yuyu-phaser-stage','v060');await expect(page.locator('#cabinet-phaser-stage canvas')).toBeVisible();
 await shot(page,'00-idle-phaser-compositor');await page.locator('#bet').tap();await shot(page,'01-bet-phaser-compositor');await page.locator('#start').tap();await expect(page.locator('#status')).toContainText('REELS SPINNING');await waitLog(page,'REEL_SPEED  LAUNCH:84');
 const launch=await state(page),speed0=launch.reels.map(r=>r.speed),travel0=launch.reels.map(r=>r.travel);
 await expect.poll(async()=>{const x=await state(page);return x.reels.every((r,i)=>r.speed>84&&r.travel>travel0[i]+8)&&x.phaser.spinTravel>10},{timeout:1800}).toBe(true);
 const accel=await state(page),speed1=accel.reels.map(r=>r.speed),travel1=accel.reels.map(r=>r.travel);expect(speed1.every(v=>v>84)).toBe(true);expect(travel1.every((v,i)=>v>travel0[i]+8)).toBe(true);await shot(page,'02a-accelerating-phaser-compositor');
 await waitLog(page,'REEL_SPEED  CRUISE_R1:520');await waitLog(page,'REEL_SPEED  CRUISE_R2:538');await waitLog(page,'REEL_SPEED  CRUISE_R3:556');const cruise=await state(page);expect(cruise.reels.every(r=>r.stage==='cruise')).toBe(true);await shot(page,'02b-cruise-phaser-compositor');
 const brakeEvidence=[];for(let i=0;i<3;i++){const before=await state(page),beforeSpeed=before.reels[i].speed;await page.locator('.stop').nth(i).tap();await waitLog(page,`REEL_BRAKE  R${i+1}:`);await page.waitForTimeout(55);const mid=await state(page);expect(mid.reels[i].speed).toBeLessThan(beforeSpeed);await waitLog(page,`REEL_SETTLE  R${i+1}->`);await waitLog(page,`LOCK  ${i+1}`);s=await state(page);expect(s.reels[i].locked).toBe(true);expect(s.reels[i].latticeError).toBeLessThanOrEqual(.001);brakeEvidence.push({beforeSpeed,midSpeed:mid.reels[i].speed,lockedTravel:s.reels[i].travel});await shot(page,`0${i+4}-stop${i+1}-phaser-compositor`);}
 await expect(page.locator('#machine')).toHaveAttribute('data-phase','bonus',{timeout:3000});await waitLog(page,'PHASER_FX  BONUS_BURST');await waitLog(page,'YUYU  FLOWER_LAMP_ON');await waitLog(page,'CABINET_STAGE_BONUS  LENS_TWEEN');await page.waitForTimeout(350);s=await state(page);expect(s.lamp).toBe(true);expect(s.locks.every(Boolean)).toBe(true);expect(s.audio.hasContext).toBe(true);expect(s.audio.contextState).toBe('running');expect(s.cabinetStage.errors).toEqual([]);await expect(page.locator('.flower.on')).toHaveCount(2);await shot(page,'07-bonus-lamps-phaser-compositor');
 fs.writeFileSync(path.join(evidenceDir,'yuyu-report.json'),JSON.stringify({url,state:s,cabinetStage:s.cabinetStage,cabinetPhysical:s.cabinetPhysical,symbolProportion:s.symbolProportion,symbolSpacing:s.symbolSpacing,symbolPrint:s.symbolPrint,reference:s.reference,motion:{speed0,speed1,travel0,travel1,brakeEvidence},consoleMessages,pageErrors,eventLog:await page.locator('#eventLog').textContent()},null,2));
 expect(pageErrors).toEqual([]);expect(consoleMessages.filter(x=>/error|exception/i.test(x))).toEqual([]);
});